### ISSUE TITLE
Add YajHFC to Brew

### ISSUE THREAD

**Issue by Lucurus** [jwolz/yajhfc#67]
Hi, I was wondering if you would consider adding YajHFC to the MacOS package manager [Brew](https://brew.sh)?

**Comment by jwolz** [comment]
I would like to put it that way:
If someone wants to create a package for Brew, it would be great, and I can offer some help if questions regarding YajHFC arise.

I won't do that myself, however.
Reason is that I don't know Brew and currently don't use MacOS myself, so it would be a quite a bit work for me to create such a package and especially to support it later.

**Comment by Lucurus** [comment]
Thanks for the reply!

Fully understood, I can do the setup but I cannot guarantee that I can maintain it so I would suggest closing the Issue, or should I leave it open in case anyone else would like to?

Thanks for your great work!

**Comment by jwolz** [comment]
Closing the issue.
