### ISSUE TITLE
ubuntu 20.04 hylafax server - can't read log files

### ISSUE THREAD

**Issue by kencu** [jwolz/yajhfc#72]
yahfc 0.6.3, hylafax-server 6.0.6:

```
# apt list hylafax-server
Listing... Done
hylafax-server/focal,now 3:6.0.6-8.1build1 amd64 [installed]
```

I don't seem to be able to view the logs on received faxes, even if in "admin mode":

![Screen Shot 2021-12-26 at 5 57 22 PM](https://user-images.githubusercontent.com/21211439/147427099-dfa95dc6-91f8-4c95-be0e-d6293fc8bcbc.png)

I have the permissions on the folders pretty stock, as installed by the hylafax-server deb on Ubuntu 20.04:

````
root@ubuntuserver:/var/spool/hylafax# ls -la
total 68
drwxrwxr-x 17 uucp uucp 4096 Dec 25 23:20 .
drwxr-xr-x  8 root root 4096 Dec 25 23:16 ..
prw-------  1 uucp uucp    0 Dec 26 17:55 FIFO
prw-------  1 uucp uucp    0 Dec 25 23:20 FIFO.ttyS5
drwxr-xr-x  2 uucp uucp 4096 Sep  5  2019 archive
drwxr-xr-x  2 root root 4096 Dec 25 23:16 bin
drwxr-xr-x  2 uucp uucp 4096 Dec 26 18:04 client
drwxr-xr-x  2 uucp uucp 4096 Dec 25 23:16 config
drwxr-xr-x  2 uucp uucp 4096 Dec 25 23:16 dev
drwxr-xr-x  2 uucp uucp 4096 Sep  5  2019 docq
drwxr-xr-x  2 uucp uucp 4096 Sep  5  2019 doneq
drwxr-xr-x  3 root root 4096 Dec 26 10:52 etc
drwxr-xr-x  2 uucp uucp 4096 Sep  5  2019 info
drwxr-xr-x  2 uucp uucp 4096 Dec 26 17:52 log
drwxr-xr-x  2 uucp uucp 4096 Sep  5  2019 pollq
drwxr-xr-x  2 uucp uucp 4096 Dec 26 17:56 recvq
drwxr-xr-x  2 uucp uucp 4096 Sep  5  2019 sendq
drwxr-xr-x  2 uucp uucp 4096 Dec 26 06:47 status
drwxrwxrwt  2 uucp uucp 4096 Dec 25 23:32 tmp
````

I had the logfile permissions set at the defaults (0600) and then tried liberalizing them a bit to this, but it made no different to yajhfc:
```
RecvFileMode:		0644
LogFileMode:		0644
DeviceMode:		0666
```

```
root@ubuntuserver:/var/spool/hylafax/log# ls -la
total 248
drwxr-xr-x  2 uucp uucp   4096 Dec 26 17:52 .
drwxrwxr-x 17 uucp uucp   4096 Dec 25 23:20 ..
-rw-------  1 uucp uucp  10723 Dec 25 23:48 c000000001
-rw-------  1 uucp uucp  13842 Dec 25 23:59 c000000002
-rw-r--r--  1 uucp uucp 107295 Dec 26 00:10 c000000003
-rw-r--r--  1 uucp uucp  24258 Dec 26 05:49 c000000004
-rw-r--r--  1 uucp uucp   3660 Dec 26 10:44 c000000005
-rw-r--r--  1 uucp uucp   3660 Dec 26 10:48 c000000006
-rw-r--r--  1 uucp uucp   3660 Dec 26 17:34 c000000007
-rw-r--r--  1 uucp uucp  55060 Dec 26 17:55 c000000008
-rw-------  1 uucp uucp      1 Dec 26 17:52 seqf
-rw-------  1 uucp uucp   1773 Dec 26 17:55 xferfaxlog
```

am I missing something in setup?

Thanks for YajHFC -- I've been using it for years now!

**Comment by jwolz** [comment]
The permissions are fine. If it were a permissions problem, you would get an error message like "permission denied".

The problem is that the "view log" option does only work on sent faxes, but not on received ones. 
The reason for this is that Hylafax does not give the client the information which log file belongs to which received fax. 
So YajHFC can't find out which log it would need to show when you select this option.
(for sent faxes the client can get an ID which corresponds to the log file name, for received ones you only get the file name in recvq which has a numbering independent from the logs.)

**Comment by kencu** [comment]
thanks. I have sent about 50,000 faxes but only recently enabled fax receiving when I upgraded to an Ubuntu server and Multitech modem. Was pulling my hair out about this!
